# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rruzAZOyJy1YOoGbh5vpz-OYphtu8hqS
"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

df=pd.read_csv("/content/sample_data/diabetes.csv")

df.head()

df.info()

df.describe().T

df.tail()

df.shape

df.shape

df.info()

df.columns

df.isnull().sum()

df.nunique()

df['Age']

df['BMI']

df.duplicated().sum()

df.columns

df['Insulin']

df.corr().T

df.hist(figsize=(10,10))
plt.show()

plt.figure(figsize=(7,7))
sns.heatmap(df.corr(),annot=True,cmap='coolwarm')
plt.show()

df.head()

df.describe()

plt.boxplot(df['Age'])
plt.show()

df.head()

X=df.drop('Outcome',axis=1)

y=df['Outcome']

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

x_shape=X_train.shape

y_test

y_train.shape,X_test.shape,X_train.shape

y_train.shape,X_test.shape,X_train.shape,y_test.shape

from sklearn.tree import DecisionTreeClassifier

dtc_cart = DecisionTreeClassifier(criterion='gini')

dtc_cart

dtc_cart.fit(X_train,y_train)

dtc_cart.score(X_test,y_test)*100

from sklearn import tree

dtc_cart

tree.plot_tree(dtc_cart,)
plt.show()

